version: '3'

services:
  cash:
    image: python
    container_name: cash
    command: bash -c "cd /src/ && pip install -i https://pypi.doubanio.com/simple/ -r requirements.txt && make migrate && make start"
    volumes:
      - ./:/src
    environment:
      CASH_PROFILE: demo

  lb:
    image: nginx
    container_name: cash_lb
    links:
      - cash
    ports:
      - "9080:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/src
    depends_on:
      - cash
